"""
This type stub file was generated by pyright.
"""

from googleapiclient import _helpers as util

"""Errors for the library.

All exceptions defined by the library
should be defined in this file.
"""
__author__ = ...
class Error(Exception):
    """Base error for this module."""
    ...


class HttpError(Error):
    """HTTP data was invalid or unexpected."""
    @util.positional(3)
    def __init__(self, resp, content, uri=...) -> None:
        ...

    @property
    def status_code(self):
        """Return the HTTP status code from the response content."""
        ...

    def __repr__(self): # -> str:
        ...

    __str__ = ...


class InvalidJsonError(Error):
    """The JSON returned could not be parsed."""
    ...


class UnknownFileType(Error):
    """File type unknown or unexpected."""
    ...


class UnknownLinkType(Error):
    """Link type unknown or unexpected."""
    ...


class UnknownApiNameOrVersion(Error):
    """No API with that name and version exists."""
    ...


class UnacceptableMimeTypeError(Error):
    """That is an unacceptable mimetype for this operation."""
    ...


class MediaUploadSizeError(Error):
    """Media is larger than the method can accept."""
    ...


class ResumableUploadError(HttpError):
    """Error occurred during resumable upload."""
    ...


class InvalidChunkSizeError(Error):
    """The given chunksize is not valid."""
    ...


class InvalidNotificationError(Error):
    """The channel Notification is invalid."""
    ...


class BatchError(HttpError):
    """Error occurred during batch operations."""
    @util.positional(2)
    def __init__(self, reason, resp=..., content=...) -> None:
        ...

    def __repr__(self): # -> LiteralString:
        ...

    __str__ = ...


class UnexpectedMethodError(Error):
    """Exception raised by RequestMockBuilder on unexpected calls."""
    @util.positional(1)
    def __init__(self, methodId=...) -> None:
        """Constructor for an UnexpectedMethodError."""
        ...



class UnexpectedBodyError(Error):
    """Exception raised by RequestMockBuilder on unexpected bodies."""
    def __init__(self, expected, provided) -> None:
        """Constructor for an UnexpectedMethodError."""
        ...



