"""
This type stub file was generated by pyright.
"""

__all__ = ['ThingsNobodyCaresAboutButMe', 'CharacterEncodingOverride', 'CharacterEncodingUnknown', 'NonXMLContentType', 'UndeclaredNamespace']
class ThingsNobodyCaresAboutButMe(Exception):
    ...


class CharacterEncodingOverride(ThingsNobodyCaresAboutButMe):
    ...


class CharacterEncodingUnknown(ThingsNobodyCaresAboutButMe):
    ...


class NonXMLContentType(ThingsNobodyCaresAboutButMe):
    ...


class UndeclaredNamespace(Exception):
    ...


