"""
This type stub file was generated by pyright.
"""

class FeedParserDict(dict):
    keymap = ...
    def __getitem__(self, key): # -> list[FeedParserDict]:
        """
        :return: A :class:`FeedParserDict`.
        """
        ...

    def __contains__(self, key): # -> bool:
        ...

    has_key = ...
    def get(self, key, default=...): # -> list[FeedParserDict] | None:
        """
        :return: A :class:`FeedParserDict`.
        """
        ...

    def __setitem__(self, key, value): # -> None:
        ...

    def setdefault(self, k, default): # -> list[FeedParserDict]:
        ...

    def __getattr__(self, key): # -> list[FeedParserDict]:
        ...

    def __hash__(self) -> int:
        ...



