"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class ArcgisResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def address(self):
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def score(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | dict[Any, Any] | None:
        ...



class ArcgisQuery(MultipleResultsQuery):
    """
    ArcGIS REST API
    =======================
    The World Geocoding Service finds addresses and places in all supported countries
    from a single endpoint. The service can find point locations of addresses,
    business names, and so on.  The output points can be visualized on a map,
    inserted as stops for a route, or loaded as input for a spatial analysis.
    an address, retrieving imagery metadata, or creating a route.

    API Reference
    -------------
    https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = ArcgisResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
    g = ...
