"""
This type stub file was generated by pyright.
"""

from geocoder.base import OneResult
from geocoder.arcgis import ArcgisQuery

class ArcgisReverseResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self):
        ...

    @property
    def city(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def region(self):
        ...

    @property
    def country(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def state(self):
        ...



class ArcgisReverse(ArcgisQuery):
    """
    ArcGIS REST API
    =======================
    The World Geocoding Service finds addresses and places in all supported countries
    from a single endpoint. The service can find point locations of addresses,
    business names, and so on.  The output points can be visualized on a map,
    inserted as stops for a route, or loaded as input for a spatial analysis.
    an address, retrieving imagery metadata, or creating a route.

    API Reference
    -------------
    https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = ArcgisReverseResult


if __name__ == '__main__':
    g = ...
