"""
This type stub file was generated by pyright.
"""

from geocoder.base import OneResult
from geocoder.baidu import BaiduQuery

class BaiduReverseResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def address(self):
        ...

    @property
    def country(self):
        ...

    @property
    def province(self):
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def district(self):
        ...

    @property
    def street(self):
        ...

    @property
    def housenumber(self):
        ...



class BaiduReverse(BaiduQuery):
    """
    Baidu Geocoding API
    ===================
    Baidu Maps Geocoding API is a free open the API, the default quota
    one million times / day.

    Params
    ------
    :param location: Your search location you want geocoded.
    :param key: Baidu API key.
    :param referer: Baidu API referer website.

    References
    ----------
    API Documentation: http://developer.baidu.com/map
    Get Baidu Key: http://lbsyun.baidu.com/apiconsole/key
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = BaiduReverseResult


if __name__ == '__main__':
    g = ...
