"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class BaiduResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def confidence(self):
        ...



class BaiduQuery(MultipleResultsQuery):
    """
    Baidu Geocoding API
    ===================
    Baidu Maps Geocoding API is a free open the API, the default quota
    one million times / day.

    Params
    ------
    :param location: Your search location you want geocoded.
    :param key: Baidu API key.
    :param referer: Baidu API referer website.

    References
    ----------
    API Documentation: http://developer.baidu.com/map
    Get Baidu Key: http://lbsyun.baidu.com/apiconsole/key
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = BaiduResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
