"""
This type stub file was generated by pyright.
"""

from geocoder.bing_batch import BingBatch, BingBatchResult

PY2 = ...
csv_io = ...
csv_encode = ...
csv_decode = ...
class BingBatchReverseResult(BingBatchResult):
    @property
    def address(self): # -> None:
        ...

    @property
    def city(self): # -> None:
        ...

    @property
    def postal(self): # -> None:
        ...

    @property
    def state(self): # -> None:
        ...

    @property
    def country(self): # -> None:
        ...

    @property
    def ok(self): # -> bool:
        ...

    def debug(self, verbose=...): # -> list[None]:
        ...



class BingBatchReverse(BingBatch):
    method = ...
    _RESULT_CLASS = BingBatchReverseResult
    def generate_batch(self, locations):
        ...



if __name__ == '__main__':
    g = ...
