"""
This type stub file was generated by pyright.
"""

from geocoder.bing_batch import BingBatch, BingBatchResult

PY2 = ...
csv_io = ...
csv_encode = ...
csv_decode = ...
class BingBatchForwardResult(BingBatchResult):
    @property
    def lat(self): # -> float | None:
        ...

    @property
    def lng(self): # -> float | None:
        ...

    @property
    def ok(self): # -> bool:
        ...

    def debug(self, verbose=...): # -> list[None]:
        ...



class BingBatchForward(BingBatch):
    method = ...
    _RESULT_CLASS = BingBatchForwardResult
    def generate_batch(self, addresses):
        ...



if __name__ == '__main__':
    g = ...
