"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class BingResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self): # -> None:
        ...

    @property
    def lng(self): # -> None:
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self): # -> str | None:
        ...

    @property
    def street(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def accuracy(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | dict[Any, Any] | None:
        ...



class BingQuery(MultipleResultsQuery):
    """
    Bing Maps REST Services
    =======================
    The Bing™ Maps REST Services Application Programming Interface (API)
    provides a Representational State Transfer (REST) interface to
    perform tasks such as creating a static map with pushpins, geocoding
    an address, retrieving imagery metadata, or creating a route.

    API Reference
    -------------
    http://msdn.microsoft.com/en-us/library/ff701714.aspx

    Get Bing key
    ------------
    https://www.bingmapsportal.com/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = BingResult
    _KEY = ...


class BingQueryDetail(MultipleResultsQuery):
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = BingResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
