"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

PY2 = ...
csv_io = ...
LOGGER = ...
class BingBatchResult(OneResult):
    def __init__(self, content) -> None:
        ...

    @property
    def lat(self): # -> None:
        ...

    @property
    def lng(self): # -> None:
        ...

    def debug(self, verbose=...): # -> list[None]:
        ...



class BingBatch(MultipleResultsQuery):
    """
    Bing Maps REST Services
    =======================
    The Bing™ Maps REST Services Application Programming Interface (API)
    provides a Representational State Transfer (REST) interface to
    perform tasks such as creating a static map with pushpins, geocoding
    an address, retrieving imagery metadata, or creating a route.

    API Reference
    -------------
    http://msdn.microsoft.com/en-us/library/ff701714.aspx

    Dataflow Reference
    ------------------
    https://msdn.microsoft.com/en-us/library/ff701733.aspx

    """
    provider = ...
    _URL = ...
    _BATCH_TIMEOUT = ...
    _BATCH_WAIT = ...
    _RESULT_CLASS = BingBatchResult
    _KEY = ...
    def extract_resource_id(self, response):
        ...

    def is_job_done(self, job_id):
        ...

    def get_job_result(self, job_id):
        ...



