"""
This type stub file was generated by pyright.
"""

from geocoder.bing import BingQuery, BingResult

class BingReverseResult(BingResult):
    @property
    def ok(self): # -> bool:
        ...



class BingReverse(BingQuery):
    """
    Bing Maps REST Services
    =======================
    The Bing™ Maps REST Services Application Programming Interface (API)
    provides a Representational State Transfer (REST) interface to
    perform tasks such as creating a static map with pushpins, geocoding
    an address, retrieving imagery metadata, or creating a route.

    API Reference
    -------------
    http://msdn.microsoft.com/en-us/library/ff701714.aspx

    """
    provider = ...
    method = ...
    _URL = ...


if __name__ == '__main__':
    g = ...
