"""
This type stub file was generated by pyright.
"""

AVG_EARTH_RADIUS = ...
def Distance(*args, **kwargs): # -> float:
    ...

def haversine(point1, point2, **kwargs): # -> float | None:
    """ Calculate the great-circle distance bewteen two points on the Earth surface.

    :input: two 2-tuples, containing the latitude and longitude of each point
    in decimal degrees.

    Example: haversine((45.7597, 4.8422), (48.8567, 2.3508))

    :output: Returns the distance bewteen the two points.
    The default unit is kilometers. Miles can be returned
    if the ``miles`` parameter is set to True.

    """
    ...

if __name__ == '__main__':
    d = ...
