"""
This type stub file was generated by pyright.
"""

import ratelim
from geocoder.base import MultipleResultsQuery, OneResult

class FreeGeoIPResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self): # -> str:
        ...

    @property
    def postal(self): # -> None:
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def region_code(self):
        ...

    @property
    def country(self):
        ...

    @property
    def country_code3(self):
        ...

    @property
    def continent(self):
        ...

    @property
    def timezone(self):
        ...

    @property
    def area_code(self):
        ...

    @property
    def dma_code(self):
        ...

    @property
    def offset(self):
        ...

    @property
    def organization(self):
        ...

    @property
    def ip(self):
        ...

    @property
    def time_zone(self):
        ...



class FreeGeoIPQuery(MultipleResultsQuery):
    """
    FreeGeoIP.net
    =============
    freegeoip.net provides a public HTTP API for software developers to
    search the geolocation of IP addresses. It uses a database of IP addresses
    that are associated to cities along with other relevant information like
    time zone, latitude and longitude.

    You're allowed up to 10,000 queries per hour by default. Once this
    limit is reached, all of your requests will result in HTTP 403,
    forbidden, until your quota is cleared.

    API Reference
    -------------
    http://freegeoip.net/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = FreeGeoIPResult
    _KEY_MANDATORY = ...
    @staticmethod
    @ratelim.greedy(10000, 60 * 60)
    def rate_limited_get(*args, **kwargs): # -> Response:
        ...



if __name__ == '__main__':
    g = ...
