"""
This type stub file was generated by pyright.
"""

from geocoder.base import OneResult
from geocoder.gaode import GaodeQuery

class GaodeReverseResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def address(self):
        ...

    @property
    def country(self):
        ...

    @property
    def province(self):
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def district(self):
        ...

    @property
    def street(self):
        ...

    @property
    def adcode(self):
        ...

    @property
    def township(self):
        ...

    @property
    def towncode(self):
        ...

    @property
    def housenumber(self):
        ...



class GaodeReverse(GaodeQuery):
    """
    Gaode GeoReverse API
    ===================
    Gaode Maps GeoReverse API is a free open the API, the default quota
    2000 times / day.

    Params
    ------
    :param location: Your search location you want geocoded.
    :param key: Gaode API key.
    :param referer: Gaode API referer website.

    References
    ----------
    API Documentation: http://lbs.amap.com/api/webservice/guide/api/georegeo
    Get Gaode AMap Key: http://lbs.amap.com/dev/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GaodeReverseResult


if __name__ == '__main__':
    g = ...
