"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class GaodeResult(OneResult):
    @property
    def lat(self): # -> float:
        ...

    @property
    def lng(self): # -> float:
        ...

    @property
    def quality(self):
        ...

    @property
    def address(self):
        ...

    @property
    def country(self): # -> Literal['中国']:
        ...

    @property
    def province(self):
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def district(self):
        ...

    @property
    def street(self):
        ...

    @property
    def adcode(self):
        ...

    @property
    def housenumber(self):
        ...



class GaodeQuery(MultipleResultsQuery):
    """
    Gaode AMap Geocoding API
    ===================
    Gaode Maps Geocoding API is a free open the API, the default quota
    2000 times / day.

    Params
    ------
    :param location: Your search location you want geocoded.
    :param key: Gaode API key.

    References
    ----------
    API Documentation: http://lbs.amap.com/api/webservice/guide/api/georegeo
    Get AMap Key: http://lbs.amap.com/dev/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GaodeResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
