"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class GeolyticaResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self): # -> float | None:
        ...

    @property
    def lng(self): # -> float | None:
        ...

    @property
    def postal(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def address(self): # -> LiteralString | Literal['']:
        ...



class GeolyticaQuery(MultipleResultsQuery):
    """
    Geocoder.ca
    ===========
    A Canadian and US location geocoder.

    API Reference
    -------------
    http://geocoder.ca/?api=1
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GeolyticaResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
