"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

LOGGER = ...
class GeonamesResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def geonames_id(self):
        ...

    @property
    def address(self):
        ...

    @property
    def feature_class(self):
        ...

    @property
    def class_description(self):
        ...

    @property
    def code(self):
        ...

    @property
    def description(self):
        ...

    @property
    def state(self):
        ...

    @property
    def state_code(self):
        ...

    @property
    def country(self):
        ...

    @property
    def country_code(self):
        ...

    @property
    def population(self):
        ...



class GeonamesQuery(MultipleResultsQuery):
    """
    GeoNames REST Web Services
    ==========================
    GeoNames is mainly using REST webservices. Find nearby postal codes / reverse geocoding
    This service comes in two flavors.You can either pass the lat/long or a postalcode/placename.

    API Reference
    -------------
    http://www.geonames.org/export/web-services.html
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GeonamesResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
