"""
This type stub file was generated by pyright.
"""

from geocoder.geonames import GeonamesQuery

class GeonamesChildren(GeonamesQuery):
    """ Children:
        http://api.geonames.org/childrenJSON?formatted=true&geonameId=6094817
    """
    provider = ...
    method = ...
    _URL = ...


if __name__ == '__main__':
    g = ...
    c = ...
