"""
This type stub file was generated by pyright.
"""

from geocoder.geonames_children import GeonamesChildren

class GeonamesHierarchy(GeonamesChildren):
    """ Hierarchy:
        http://api.geonames.org/hierarchyJSON?formatted=true&geonameId=6094817
    """
    provider = ...
    method = ...
    _URL = ...


if __name__ == '__main__':
    c = ...
