"""
This type stub file was generated by pyright.
"""

from geocoder.geonames import GeonamesQuery, GeonamesResult

class GeonamesFullResult(GeonamesResult):
    """ Get more information for given geonames_id, e.g timzone and administrative hierarchy"""
    @property
    def continent(self):
        ...

    @property
    def country_geonames_id(self):
        ...

    @property
    def state_geonames_id(self):
        ...

    @property
    def admin2(self):
        ...

    @property
    def admin2_geonames_id(self):
        ...

    @property
    def admin3(self):
        ...

    @property
    def admin3_geonames_id(self):
        ...

    @property
    def admin4(self):
        ...

    @property
    def admin4_geonames_id(self):
        ...

    @property
    def admin5(self):
        ...

    @property
    def admin5_geonames_id(self):
        ...

    @property
    def srtm3(self):
        ...

    @property
    def wikipedia(self):
        ...

    @property
    def timeZoneId(self): # -> None:
        ...

    @property
    def timeZoneName(self): # -> None:
        ...

    @property
    def rawOffset(self): # -> None:
        ...

    @property
    def dstOffset(self): # -> None:
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | dict[Any, Any]:
        ...



class GeonamesDetails(GeonamesQuery):
    """ Details:
        http://api.geonames.org/getJSON?geonameId=6094817&style=full
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GeonamesFullResult


if __name__ == '__main__':
    c = ...
