"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class GisgraphyResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self):
        ...

    @property
    def country(self):
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def street(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def postal(self):
        ...



class GisgraphyQuery(MultipleResultsQuery):
    """
    Gisgraphy REST API
    =======================

    API Reference
    -------------
    http://www.gisgraphy.com/documentation/user-guide.php
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GisgraphyResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
