"""
This type stub file was generated by pyright.
"""

from geocoder.gisgraphy import GisgraphyQuery, GisgraphyResult

class GisgraphyReverseResult(GisgraphyResult):
    @property
    def ok(self): # -> bool:
        ...



class GisgraphyReverse(GisgraphyQuery):
    """
    Gisgraphy REST API
    =======================

    API Reference
    -------------
    http://www.gisgraphy.com/documentation/user-guide.php
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = GisgraphyReverseResult


if __name__ == '__main__':
    g = ...
