"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class TimezoneResult(OneResult):
    def __repr__(self): # -> str:
        ...

    @property
    def ok(self): # -> bool:
        ...

    @property
    def timeZoneId(self):
        ...

    @property
    def timeZoneName(self):
        ...

    @property
    def rawOffset(self):
        ...

    @property
    def dstOffset(self):
        ...



class TimezoneQuery(MultipleResultsQuery):
    """
    Google Time Zone API
    ====================
    The Time Zone API provides time offset data for locations on the surface of the earth.
    Requesting the time zone information for a specific Latitude/Longitude pair will
    return the name of that time zone, the time offset from UTC, and the Daylight Savings offset.

    API Reference
    -------------
    https://developers.google.com/maps/documentation/timezone/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = TimezoneResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
