"""
This type stub file was generated by pyright.
"""

from geocoder.google import GoogleQuery, GoogleResult

class GoogleReverseResult(GoogleResult):
    @property
    def ok(self): # -> bool:
        ...



class GoogleReverse(GoogleQuery):
    """
    Google Geocoding API
    ====================
    Geocoding is the process of converting addresses (like "1600 Amphitheatre
    Parkway, Mountain View, CA") into geographic coordinates (like latitude
    37.423021 and longitude -122.083739), which you can use to place markers or
    position the map.

    API Reference
    -------------
    https://developers.google.com/maps/documentation/geocoding/
    """
    provider = ...
    method = ...


if __name__ == '__main__':
    g = ...
