"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class ElevationResult(OneResult):
    @property
    def status(self): # -> Literal['OK', 'ERROR - No Elevation found']:
        ...

    @property
    def ok(self): # -> bool:
        ...

    @property
    def meters(self): # -> None:
        ...

    @property
    def feet(self): # -> None:
        ...

    @property
    def elevation(self):
        ...

    @property
    def resolution(self):
        ...



class ElevationQuery(MultipleResultsQuery):
    """
    Google Elevation API
    ====================
    The Elevation API provides elevation data for all locations on the surface of the
    earth, including depth locations on the ocean floor (which return negative values).
    In those cases where Google does not possess exact elevation measurements at the
    precise location you request, the service will interpolate and return an averaged
    value using the four nearest locations.

    API Reference
    -------------
    https://developers.google.com/maps/documentation/elevation/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = ElevationResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
