"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class HereResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def district(self):
        ...

    @property
    def city(self):
        ...

    @property
    def county(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def accuracy(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | dict[Any, Any]:
        ...



class HereQuery(MultipleResultsQuery):
    """
    HERE Geocoding REST API
    =======================
    Send a request to the geocode endpoint to find an address
    using a combination of country, state, county, city,
    postal code, district, street and house number.

    API Reference
    -------------
    https://developer.here.com/rest-apis/documentation/geocoder
    """
    provider = ...
    method = ...
    qualified_address = ...
    _URL = ...
    _RESULT_CLASS = HereResult


if __name__ == '__main__':
    g = ...
