"""
This type stub file was generated by pyright.
"""

from geocoder.here import HereQuery, HereResult

class HereReverseResult(HereResult):
    @property
    def ok(self): # -> bool:
        ...



class HereReverse(HereQuery):
    """
    HERE Geocoding REST API
    =======================
    Send a request to the geocode endpoint to find an address
    using a combination of country, state, county, city,
    postal code, district, street and house number.

    API Reference
    -------------
    https://developer.here.com/rest-apis/documentation/geocoder
    """
    provider = ...
    method = ...
    _RESULT_CLASS = HereReverseResult
    _URL = ...


if __name__ == '__main__':
    g = ...
