"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class IpinfoResult(OneResult):
    @property
    def lat(self): # -> Any | float | None:
        ...

    @property
    def lng(self): # -> Any | float | None:
        ...

    @property
    def address(self): # -> str:
        ...

    @property
    def postal(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def hostname(self):
        ...

    @property
    def ip(self):
        ...

    @property
    def org(self):
        ...



class IpinfoQuery(MultipleResultsQuery):
    """
    API Reference
    -------------
    https://ipinfo.io
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = IpinfoResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
