"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class KomootResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | None:
        ...

    @property
    def address(self): # -> LiteralString:
        ...

    @property
    def country(self):
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def street(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def osm_id(self):
        ...

    @property
    def osm_value(self):
        ...

    @property
    def osm_key(self):
        ...

    @property
    def osm_type(self):
        ...



class KomootQuery(MultipleResultsQuery):
    """
    Komoot REST API
    =======================

    API Reference
    -------------
    http://photon.komoot.de
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = KomootResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
