"""
This type stub file was generated by pyright.
"""

from geocoder.komoot import KomootQuery, KomootResult

class KomootReverseResult(KomootResult):
    @property
    def ok(self): # -> bool:
        ...



class KomootReverse(KomootQuery):
    """
    Komoot REST API
    =======================

    API Reference
    -------------
    http://photon.komoot.de
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = KomootReverseResult


if __name__ == '__main__':
    g = ...
