"""
This type stub file was generated by pyright.
"""

class Location:
    """ Location container """
    lat = ...
    lng = ...
    def __init__(self, location, **kwargs) -> None:
        ...

    @property
    def ok(self): # -> bool:
        ...

    @property
    def latlng(self): # -> list[float] | list[Any]:
        ...

    @property
    def latitude(self): # -> Any | float | None:
        ...

    @property
    def longitude(self): # -> Any | float | None:
        ...

    @property
    def xy(self): # -> list[float] | list[Any]:
        ...

    def __str__(self) -> str:
        ...



class BBox:
    """BBox container"""
    DEGREES_TOLERANCE = ...
    @classmethod
    def factory(cls, arg): # -> Self:
        ...

    def __init__(self, bbox=..., bounds=..., lat=..., lng=..., west=..., south=..., east=..., north=...) -> None:
        ...

    @property
    def lat(self): # -> float:
        ...

    @property
    def lng(self): # -> float:
        ...

    @property
    def latlng(self): # -> list[float] | list[Any]:
        ...

    @property
    def latitude(self): # -> float:
        ...

    @property
    def longitude(self): # -> float:
        ...

    @property
    def xy(self): # -> list[float] | list[Any]:
        ...

    @property
    def as_dict(self): # -> dict[str, list[float]]:
        ...



if __name__ == '__main__':
    l = ...
