"""
This type stub file was generated by pyright.
"""

from geocoder.locationiq import LocationIQQuery

class LocationIQReverse(LocationIQQuery):
    provider = ...
    method = ...


if __name__ == '__main__':
    g = ...
