"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class MapboxResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self): # -> None:
        ...

    @property
    def lng(self): # -> None:
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self): # -> Literal['']:
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def accuracy(self): # -> Literal['interpolated'] | None:
        ...

    @property
    def quality(self):
        ...

    @property
    def interpolated(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | dict[Any, Any] | None:
        ...



class MapboxQuery(MultipleResultsQuery):
    """
    Mapbox Geocoding
    ================
    The Mapbox Geocoding API lets you convert location text into
    geographic coordinates (1600 Pennsylvania Ave NW → -77.0366,38.8971).

    API Reference
    -------------
    https://www.mapbox.com/developers/api/geocoding/

    Get Mapbox Access Token
    -----------------------
    https://www.mapbox.com/account
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = MapboxResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
    g = ...
