"""
This type stub file was generated by pyright.
"""

from geocoder.mapbox import MapboxQuery, MapboxResult

class MapboxReverseResult(MapboxResult):
    @property
    def ok(self): # -> bool:
        ...



class MapboxReverse(MapboxQuery):
    """
    Mapbox Reverse Geocoding
    ========================
    Reverse geocoding lets you reverse this process, turning a
    pair of lat/lon coordinates into a meaningful place name
    (-77.036,38.897 → 1600 Pennsylvania Ave NW).

    API Reference
    -------------
    https://www.mapbox.com/developers/api/geocoding/

    Get Mapbox Access Token
    -----------------------
    https://www.mapbox.com/account
    """
    provider = ...
    method = ...
    _URL = ...


if __name__ == '__main__':
    g = ...
