"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class MapquestResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def street(self):
        ...

    @property
    def address(self): # -> None:
        ...

    @property
    def quality(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def city(self):
        ...

    @property
    def county(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...



class MapquestQuery(MultipleResultsQuery):
    """
    MapQuest
    ========
    The geocoding service enables you to take an address and get the
    associated latitude and longitude. You can also use any latitude
    and longitude pair and get the associated address. Three types of
    geocoding are offered: address, reverse, and batch.

    API Reference
    -------------
    http://www.mapquestapi.com/geocoding/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = MapquestResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
