"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery
from geocoder.mapquest import MapquestResult

class MapQuestBatchResult(MapquestResult):
    @property
    def ok(self): # -> bool:
        ...



class MapquestBatch(MultipleResultsQuery):
    """
    MapQuest
    ========
    The geocoding service enables you to take an address and get the
    associated latitude and longitude. You can also use any latitude
    and longitude pair and get the associated address. Three types of
    geocoding are offered: address, reverse, and batch.

    API Reference
    -------------
    http://www.mapquestapi.com/geocoding/

    """
    provider = ...
    method = ...
    _RESULT_CLASS = MapQuestBatchResult
    _URL = ...
    _TIMEOUT = ...
    _KEY = ...


if __name__ == '__main__':
    g = ...
