"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class MapzenResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]]:
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self):
        ...

    @property
    def neighbourhood(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def gid(self):
        ...

    @property
    def id(self):
        ...



class MapzenQuery(MultipleResultsQuery):
    """
    Mapzen REST API
    =======================

    API Reference
    -------------
    https://mapzen.com/documentation/search/search/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = MapzenResult
    _KEY = ...
    def __init__(self, *args, **kwargs) -> None:
        ...



if __name__ == '__main__':
    g = ...
