"""
This type stub file was generated by pyright.
"""

from geocoder.mapzen import MapzenQuery, MapzenResult

class MapzenReverseResult(MapzenResult):
    @property
    def ok(self): # -> bool:
        ...



class MapzenReverse(MapzenQuery):
    """
    Mapzen REST API
    =======================

    API Reference
    -------------
    https://mapzen.com/documentation/search/reverse/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = MapzenReverseResult


if __name__ == '__main__':
    g = ...
