"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class MaxmindResults(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def timezone(self):
        ...

    @property
    def metro_code(self):
        ...

    @property
    def domain(self):
        ...

    @property
    def isp(self):
        ...

    @property
    def organization(self):
        ...

    @property
    def ip(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def country_code(self):
        ...

    @property
    def continent(self):
        ...

    @property
    def continent_code(self):
        ...

    @property
    def address(self): # -> str:
        ...



class MaxmindQuery(MultipleResultsQuery):
    """
    MaxMind's GeoIP2
    =======================
    MaxMind's GeoIP2 products enable you to identify the location,
    organization, connection speed, and user type of your Internet
    visitors. The GeoIP2 databases are among the most popular and
    accurate IP geolocation databases available.

    API Reference
    -------------
    https://www.maxmind.com/en/geolocation_landing
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = MaxmindResults
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
