"""
This type stub file was generated by pyright.
"""

from geocoder.opencage import OpenCageQuery, OpenCageResult

class OpenCageReverseResult(OpenCageResult):
    @property
    def ok(self): # -> bool:
        ...



class OpenCageReverse(OpenCageQuery):
    """
    OpenCage Geocoding Services
    ===========================
    OpenCage Geocoder simple, easy, and open geocoding for the entire world
    Our API combines multiple geocoding systems in the background.
    Each is optimized for different parts of the world and types of requests.
    We aggregate the best results from open data sources and algorithms so you don't have to.
    Each is optimized for different parts of the world and types of requests.

    API Reference
    -------------
    https://geocoder.opencagedata.com/api
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = OpenCageReverseResult


if __name__ == '__main__':
    g = ...
