"""
This type stub file was generated by pyright.
"""

from geocoder.osm import OsmQuery

class OsmReverse(OsmQuery):
    """
    Nominatim
    =========
    Nominatim (from the Latin, 'by name') is a tool to search OSM data by name
    and address and to generate synthetic addresses of OSM points (reverse geocoding).

    API Reference
    -------------
    http://wiki.openstreetmap.org/wiki/Nominatim
    """
    provider = ...
    method = ...


if __name__ == '__main__':
    g = ...
