"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class OttawaResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def postal(self): # -> str | None:
        ...

    @property
    def housenumber(self): # -> int | None:
        ...

    @property
    def city(self): # -> Literal['Ottawa']:
        ...

    @property
    def state(self): # -> Literal['Ontario']:
        ...

    @property
    def country(self): # -> Literal['Canada']:
        ...

    @property
    def address(self):
        ...

    @property
    def accuracy(self):
        ...



class OttawaQuery(MultipleResultsQuery):
    """
    Ottawa ArcGIS REST Services
    ===========================
    Geocoding is the process of assigning a location, usually in the form of
    coordinate values (points), to an address by comparing the descriptive
    location elements in the address to those present in the reference
    material. Addresses come in many forms, ranging from the common address
    format of a house number followed by the street name and succeeding
    information to other location descriptions such as postal zone or census
    tract. An address includes any type of information that distinguishes
    a place.

    API Reference
    -------------
    http://maps.ottawa.ca/ArcGIS/rest/services/compositeLocator/GeocodeServer/findAddressCandidates
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = OttawaResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
