"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class OttawaParcelIdResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def address_id(self):
        ...



class OttawaParcelIdQuery(MultipleResultsQuery):
    _URL = ...
    _RESULT_CLASS = OttawaParcelIdResult
    _KEY_MANDATORY = ...


class OttawaParcelResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def length(self): # -> int | None:
        """Length in Feet (f)"""
        ...

    @property
    def area(self): # -> int | None:
        """Square Foot Area (sqft)"""
        ...

    @property
    def frontage(self): # -> int | None:
        """Length in Feet (f)"""
        ...

    @property
    def municipality(self): # -> None:
        ...

    @property
    def housenumber(self): # -> None:
        ...

    @property
    def suffix(self): # -> None:
        ...

    @property
    def public_land(self): # -> None:
        ...

    @property
    def street(self): # -> None:
        ...

    @property
    def legal_unit(self): # -> None:
        ...

    @property
    def pin(self): # -> None:
        ...

    @property
    def geometry(self):
        ...

    @property
    def postal(self): # -> None:
        ...



class OttawaParcelQuery(MultipleResultsQuery):
    """
    Ottawa ArcGIS REST Services
    ===========================
    Geocoding is the process of assigning a location, usually in the form of
    coordinate values (points), to an address by comparing the descriptive
    location elements in the address to those present in the reference
    material. Addresses come in many forms, ranging from the common address
    format of a house number followed by the street name and succeeding
    information to other location descriptions such as postal zone or census
    tract. An address includes any type of information that distinguishes
    a place.

    API Reference
    -------------
    http://maps.ottawa.ca/ArcGIS/rest/services/
           compositeLocator/GeocodeServer/findAddressCandidates
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = OttawaParcelResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    area = ...
    length = ...
    frontage = ...
    location = ...
    g = ...
