"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class TamuResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self): # -> float | None:
        ...

    @property
    def lng(self): # -> float | None:
        ...

    @property
    def quality(self):
        ...

    @property
    def accuracy(self):
        ...

    @property
    def confidence(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self): # -> LiteralString:
        ...

    @property
    def address(self): # -> LiteralString:
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def postal(self):
        ...

    @property
    def census_tract(self):
        ...

    @property
    def census_block(self):
        ...

    @property
    def census_msa_fips(self):
        ...

    @property
    def census_mcd_fips(self):
        ...

    @property
    def census_metdiv_fips(self):
        ...

    @property
    def census_place_fips(self):
        ...

    @property
    def census_cbsa_fips(self):
        ...

    @property
    def census_state_fips(self):
        ...

    @property
    def census_county_fips(self):
        ...

    @property
    def census_year(self):
        ...



class TamuQuery(MultipleResultsQuery):
    """
    TAMU Geocoding Services
    =======================

    Params
    ------
    :param location: The street address of the location you want geocoded.
    :param city: The city of the location to geocode.
    :param state: The state of the location to geocode.
    :param zipcode: The zipcode of the location to geocode.
    :param key: The API key (use API key "demo" for testing).

    API Reference
    -------------
    https://geoservices.tamu.edu/Services/Geocode/WebService
    """
    provider = ...
    method = ...
    CENSUSYEARS = ...
    _URL = ...
    _RESULT_CLASS = TamuResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
