"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class TgosResult(OneResult):
    def __init__(self, json_content, language) -> None:
        ...

    @property
    def quality(self):
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self): # -> int:
        ...

    @property
    def street(self): # -> str:
        ...

    @property
    def state(self):
        ...

    @property
    def city(self):
        ...

    @property
    def country(self): # -> str:
        ...

    @property
    def alley(self):
        ...

    @property
    def lane(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def number(self):
        ...

    @property
    def road(self):
        ...

    @property
    def section(self): # -> str | int | None:
        ...

    @property
    def sub_alley(self):
        ...

    @property
    def tong(self):
        ...

    @property
    def village(self):
        ...

    @property
    def county(self):
        ...

    @property
    def name(self):
        ...

    @property
    def town(self):
        ...

    @property
    def type(self):
        ...



class TgosQuery(MultipleResultsQuery):
    '''
    TGOS Geocoding Service

    TGOS Map is official map service of Taiwan.

    API Reference
    -------------
    http://api.tgos.nat.gov.tw/TGOS_MAP_API/Web/Default.aspx
    '''
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = TgosResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
