"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class TomtomResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def geohash(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def bbox(self): # -> dict[str, list[float]] | None:
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self):
        ...

    @property
    def road(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def postal(self):
        ...



class TomtomQuery(MultipleResultsQuery):
    """
    Geocoding API
    =============
    The Geocoding API gives developers access to TomTom’s first class geocoding service.
    Developers may call this service through either a single or batch geocoding request.
    This service supports global coverage, with house number level matching in over 50 countries,
    and address point matching where available.

    API Reference
    -------------
    https://developer.tomtom.com/tomtom-maps-apis-developers
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = TomtomResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
