"""
This type stub file was generated by pyright.
"""

from geocoder.base import OneResult
from geocoder.uscensus import USCensusQuery

class USCensusReverseResult(OneResult):
    @property
    def ok(self): # -> bool:
        ...

    @property
    def state(self): # -> None:
        ...

    @property
    def statenumber(self): # -> None:
        ...

    @property
    def county(self): # -> None:
        ...

    @property
    def countynumber(self): # -> None:
        ...

    @property
    def tract(self): # -> None:
        ...

    @property
    def tractnumber(self): # -> None:
        ...

    @property
    def block(self): # -> None:
        ...

    @property
    def blocknumber(self): # -> None:
        ...

    @property
    def geoid(self): # -> None:
        ...



class USCensusReverse(USCensusQuery):
    """
    US Census Geocoder REST Services
    =======================
    The Census Geocoder is an address look-up tool that converts your address to an approximate coordinate (latitude/longitude) and returns information about the address range that includes the address and the census geography the address is within. The geocoder is available as a web interface and as an API (Representational State Transfer - REST - web-based service).

    API Reference
    -------------
    https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf

    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = USCensusReverseResult


if __name__ == '__main__':
    g = ...
