"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

PY2 = ...
csv_io = ...
csv_encode = ...
csv_decode = ...
LOGGER = ...
class USCensusBatchResult(OneResult):
    def __init__(self, content) -> None:
        ...

    @property
    def lat(self): # -> float | None:
        ...

    @property
    def lng(self): # -> float | None:
        ...

    @property
    def address(self): # -> None:
        ...



class USCensusBatch(MultipleResultsQuery):
    """
    US Census Geocoder REST Services
    =======================
    The Census Geocoder is an address look-up tool that converts your address to an approximate coordinate (latitude/longitude) and returns information about the address range that includes the address and the census geography the address is within. The geocoder is available as a web interface and as an API (Representational State Transfer - REST - web-based service).

    API Reference
    -------------
    https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html

    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = USCensusBatchResult
    _KEY_MANDATORY = ...
    def generate_batch(self, locations):
        ...



if __name__ == '__main__':
    g = ...
