"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class USCensusResult(OneResult):
    def __init__(self, json_content) -> None:
        ...

    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self):
        ...

    @property
    def housenumber(self): # -> str | None:
        ...

    @property
    def fromhousenumber(self):
        ...

    @property
    def tohousenumber(self):
        ...

    @property
    def streetname(self):
        ...

    @property
    def prequalifier(self):
        ...

    @property
    def predirection(self):
        ...

    @property
    def pretype(self):
        ...

    @property
    def suffixtype(self):
        ...

    @property
    def suffixdirection(self):
        ...

    @property
    def suffixqualifier(self):
        ...

    @property
    def city(self):
        ...

    @property
    def state(self):
        ...

    @property
    def postal(self):
        ...



class USCensusQuery(MultipleResultsQuery):
    """
    US Census Geocoder REST Services
    =======================
    The Census Geocoder is an address look-up tool that converts your address to an approximate coordinate (latitude/longitude) and returns information about the address range that includes the address and the census geography the address is within. The geocoder is available as a web interface and as an API (Representational State Transfer - REST - web-based service).

    API Reference
    -------------
    https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html

    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = USCensusResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
