"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class W3WResult(OneResult):
    @property
    def lat(self): # -> None:
        ...

    @property
    def lng(self): # -> None:
        ...

    @property
    def language(self):
        ...

    @property
    def words(self):
        ...



class W3WQuery(MultipleResultsQuery):
    """
    What3Words
    ==========
    What3Words is a global grid of 57 trillion 3mx3m squares.
    Each square has a 3 word address that can be communicated quickly,
    easily and with no ambiguity.

    Addressing the world

    Everyone and everywhere now has an address

    Params
    ------
    :param location: Your search location you want geocoded.
    :param key: W3W API key.
    :param method: Chose a method (geocode, method)

    References
    ----------
    API Reference: https://docs.what3words.com/api/v2/
    Get W3W key: https://map.what3words.com/register?dev=true
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = W3WResult
    _KEY = ...


if __name__ == '__main__':
    g = ...
