"""
This type stub file was generated by pyright.
"""

from geocoder.base import MultipleResultsQuery, OneResult

class YahooResult(OneResult):
    @property
    def lat(self):
        ...

    @property
    def lng(self):
        ...

    @property
    def address(self): # -> LiteralString:
        ...

    @property
    def housenumber(self):
        ...

    @property
    def street(self):
        ...

    @property
    def neighborhood(self):
        ...

    @property
    def city(self):
        ...

    @property
    def county(self):
        ...

    @property
    def state(self):
        ...

    @property
    def country(self):
        ...

    @property
    def hash(self):
        ...

    @property
    def quality(self):
        ...

    @property
    def postal(self):
        ...



class YahooQuery(MultipleResultsQuery):
    """
    Yahoo BOSS Geo Services
    =======================
    Yahoo PlaceFinder is a geocoding Web service that helps developers make
    their applications location-aware by converting street addresses or
    place names into geographic coordinates (and vice versa).

    API Reference
    -------------
    https://developer.yahoo.com/boss/geo/
    """
    provider = ...
    method = ...
    _URL = ...
    _RESULT_CLASS = YahooResult
    _KEY_MANDATORY = ...


if __name__ == '__main__':
    g = ...
