"""
This type stub file was generated by pyright.
"""

number = ...
def next_number(path): # -> int:
    ...

def new(name=..., verbose=..., **kwargs): # -> str:
    ...

def description(**kwargs): # -> str:
    ...

