"""
This type stub file was generated by pyright.
"""

from typing import Union

class Bar:
    def __init__(self, max: Union[float, int] = ..., width: int = ..., prefix: str = ..., eta: bool = ..., decimals: int = ..., show_duration: bool = ..., average_ETA: int = ...) -> None:
        ...

    def update_eta(self, progress): # -> str:
        ...

    def __call__(self, progress: float, prefix=..., stop=...): # -> None:
        ...

    def stop(self): # -> None:
        ...



