"""
This type stub file was generated by pyright.
"""

class _LooseFeedParser:
    contentparams = ...
    def __init__(self, baseuri=..., baselang=..., encoding=..., entities=...) -> None:
        ...

    def decode_entities(self, element, data):
        ...

    @staticmethod
    def strattrs(attrs): # -> LiteralString:
        ...



