"""
This type stub file was generated by pyright.
"""

class _StrictFeedParser:
    def __init__(self, baseuri, baselang, encoding) -> None:
        ...

    def startPrefixMapping(self, prefix, uri): # -> None:
        ...

    def startElementNS(self, name, qname, attrs): # -> None:
        ...

    def characters(self, text): # -> None:
        ...

    def endElementNS(self, name, qname): # -> None:
        ...

    def error(self, exc): # -> None:
        ...

    warning = ...
    def fatalError(self, exc):
        ...



