"""
This type stub file was generated by pyright.
"""

import logging
import os

"""Caching utility for the discovery document."""
LOGGER = ...
DISCOVERY_DOC_MAX_AGE = ...
DISCOVERY_DOC_DIR = ...
def autodetect(): # -> googleapiclient.discovery_cache.appengine_memcache.Cache | googleapiclient.discovery_cache.file_cache.Cache | None:
    """Detects an appropriate cache module and returns it.

    Returns:
      googleapiclient.discovery_cache.base.Cache, a cache object which
      is auto detected, or None if no cache object is available.
    """
    ...

def get_static_doc(serviceName, version): # -> str | None:
    """Retrieves the discovery document from the directory defined in
    DISCOVERY_DOC_DIR corresponding to the serviceName and version provided.

    Args:
        serviceName: string, name of the service.
        version: string, the version of the service.

    Returns:
        A string containing the contents of the JSON discovery document,
        otherwise None if the JSON discovery document was not found.
    """
    ...

