"""
This type stub file was generated by pyright.
"""

from . import base

"""App Engine memcache based cache for the discovery document."""
LOGGER = ...
NAMESPACE = ...
class Cache(base.Cache):
    """A cache with app engine memcache API."""
    def __init__(self, max_age) -> None:
        """Constructor.

        Args:
          max_age: Cache expiration in seconds.
        """
        ...

    def get(self, url): # -> None:
        ...

    def set(self, url, content): # -> None:
        ...



cache = ...
