"""
This type stub file was generated by pyright.
"""

import abc

"""An abstract class for caching the discovery document."""
class Cache:
    """A base abstract cache class."""
    __metaclass__ = abc.ABCMeta
    @abc.abstractmethod
    def get(self, url):
        """Gets the content from the memcache with a given key.

        Args:
          url: string, the key for the cache.

        Returns:
          object, the value in the cache for the given key, or None if the key is
          not in the cache.
        """
        ...

    @abc.abstractmethod
    def set(self, url, content):
        """Sets the given key and content in the cache.

        Args:
          url: string, the key for the cache.
          content: string, the discovery document.
        """
        ...



