"""
This type stub file was generated by pyright.
"""

from . import base

"""File based cache for the discovery document.

The cache is stored in a single file so that multiple processes can
share the same cache. It locks the file whenever accessing to the
file. When the cache content is corrupted, it will be initialized with
an empty cache.
"""
LOGGER = ...
FILENAME = ...
EPOCH = ...
class Cache(base.Cache):
    """A file based cache for the discovery documents."""
    def __init__(self, max_age) -> None:
        """Constructor.

        Args:
          max_age: Cache expiration in seconds.
        """
        ...

    def get(self, url): # -> Any | None:
        ...

    def set(self, url, content): # -> None:
        ...



cache = ...
